name: Deploy React App to Azure Web App

on:
  push:
    branches:
      - main  # Branch ที่ต้องการให้ Workflow ทำงาน

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # เพิ่ม Timeout เป็น 30 นาที

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # ใช้ Node.js เวอร์ชันที่เหมาะสม

    - name: Install dependencies
      run: npm install  # ติดตั้ง dependencies จาก package.json

    - name: Install react-scripts (if missing)
      run: npm install react-scripts --save  # ติดตั้ง react-scripts

    - name: Build React app
      run: |
        ls public  # ตรวจสอบว่าโฟลเดอร์ public มีไฟล์ index.html
        npm run build  # สร้างโฟลเดอร์ build

    - name: Debug Build Directory
      run: |
        echo "Contents of build directory:"
        ls build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: Sensor-Web-App1  # ชื่อจริงของ Azure Web App
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        enable-zip-deploy: true  # บังคับใช้ ZIP Deploy
